(function(){
const T={
en:["📖 Windi Chronicle – Our guests' stories","Wachau experiences to read","Photos, hikes, bike tours and special encounters with the Windis – from guests for guests.","➕ Tell my story","🔒 Administration","Tell my story","Title","Story","Category","First name (optional)","Publish anonymously","Photos – maximum 10","⏳ Send story for review","Cancel","⏳ Thank you! Your story will be reviewed and published afterwards."],
cz:["📖 Windi kronika – Příběhy našich hostů","Zážitky z Wachau k přečtení","Fotografie, túry, cyklovýlety a zvláštní setkání s Windis – od hostů pro hosty.","➕ Vyprávět svůj zážitek","🔒 Administrace","Vyprávět svůj zážitek","Název","Příběh","Kategorie","Křestní jméno (volitelné)","Publikovat anonymně","Fotografie – maximálně 10","⏳ Odeslat ke kontrole","Zrušit","⏳ Děkujeme! Váš příspěvek bude zkontrolován a poté zveřejněn."],
sk:["📖 Windi kronika – Príbehy našich hostí","Zážitky z Wachau na čítanie","Fotografie, túry, cyklovýlety a výnimočné stretnutia s Windis – od hostí pre hostí.","➕ Porozprávať svoj zážitok","🔒 Administrácia","Porozprávať svoj zážitok","Názov","Príbeh","Kategória","Krstné meno (voliteľné)","Publikovať anonymne","Fotografie – maximálne 10","⏳ Odoslať na kontrolu","Zrušiť","⏳ Ďakujeme! Váš príspevok skontrolujeme a následne zverejníme."],
hu:["📖 Windi-krónika – Vendégeink történetei","Wachaui élmények olvasásra","Fotók, túrák, kerékpározások és különleges találkozások a Windikkel – vendégektől vendégeknek.","➕ Elmesélem az élményem","🔒 Adminisztráció","Elmesélem az élményem","Cím","Történet","Kategória","Keresztnév (nem kötelező)","Névtelen közzététel","Fotók – legfeljebb 10","⏳ Beküldés ellenőrzésre","Mégse","⏳ Köszönjük! A bejegyzést ellenőrizzük, majd közzétesszük."],
es:["📖 Crónica Windi – Historias de nuestros huéspedes","Experiencias de Wachau para leer","Fotos, caminatas, rutas en bicicleta y encuentros especiales con los Windis – de huéspedes para huéspedes.","➕ Contar mi experiencia","🔒 Administración","Contar mi experiencia","Título","Historia","Categoría","Nombre (opcional)","Publicar anónimamente","Fotos – máximo 10","⏳ Enviar para revisión","Cancelar","⏳ ¡Gracias! Revisaremos tu publicación antes de publicarla."],
fr:["📖 Chronique Windi – Les histoires de nos hôtes","Expériences de la Wachau à lire","Photos, randonnées, circuits à vélo et rencontres avec les Windis – par des hôtes, pour des hôtes.","➕ Raconter mon expérience","🔒 Administration","Raconter mon expérience","Titre","Histoire","Catégorie","Prénom (facultatif)","Publier anonymement","Photos – 10 maximum","⏳ Envoyer pour vérification","Annuler","⏳ Merci ! Votre contribution sera vérifiée puis publiée."]};
const DE=["📖 Windi-Chronik – Die Geschichten unserer Gäste","Wachau-Erlebnisse zum Nachlesen","Fotos, Wanderungen, Radtouren und besondere Begegnungen mit den Windis – von Gästen für Gäste.","➕ Mein Erlebnis erzählen","🔒 Administration","Mein Erlebnis erzählen","Titel","Geschichte","Kategorie","Vorname (freiwillig)","Anonym veröffentlichen","Fotos – maximal 10","⏳ Beitrag zur Prüfung senden","Abbrechen","⏳ Vielen Dank! Dein Beitrag wird geprüft und anschließend veröffentlicht."];
function apply(lang){if(!T[lang])return;const map=new Map(DE.map((v,i)=>[v,T[lang][i]]));const root=document.getElementById("chronik");if(!root)return;const w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let n;while(n=w.nextNode()){const raw=n.nodeValue.trim();if(map.has(raw))n.nodeValue=n.nodeValue.replace(raw,map.get(raw))}}
const wait=setInterval(()=>{if(typeof window.setLang!=="function")return;clearInterval(wait);const base=window.setLang;window.setLang=function(lang){base(lang);setTimeout(()=>apply(lang),10)};const saved=localStorage.getItem("zabLang")||"de";setTimeout(()=>apply(saved==="cs"?"cz":saved),30)},5);
})();
